# Arrays
- A single or multidimensional structure containing data of the same type (strings, characters, integers, floats, etc.). Arrays can also be **multidimensional**, such as a 2 x 2 x 2 array.

```R
# Create an array
movie_vector <- c("Toy Story", "Akira", "The Breakfast Club", "The Artist", "Modern Times")
movie_vector <- array(movie_vector, dim = c(2, 3, 2))

# [,,1]
#      [,1]                  [,2]                  [,3]
# [1,] "Toy Story"            "The Breakfast Club" "Modern Times"
# [2,] "Akira"                "The Artist"         "Toy Story"
#
# [,,2]
#      [,1]                  [,2]                  [,3]
# [1,] "The Breakfast Club" "Modern Times"        "Akira"
# [2,] "The Artist"         "Toy Story"           "The Breakfast Club"
```

## What is the difference between an array and a vector?

Vectors are always one dimensional like a single row of data. On the other hand, an array can be multidimensional (stored as rows and columns). The "dimension" indicates how many rows of data there are.

- Let's see another example:

```R
movie_array <- array(movie_vector, dim = c(4,3))
movie_array

#      [,1]                  [,2]                  [,3]
# [1,] "Toy Story"            "The Breakfast Club" "Modern Times"
# [2,] "Akira"                "The Artist"         "Toy Story"
# [3,] "The Breakfast Club"   "Modern Times"       "Akira"
# [4,] "The Artist"           "Toy Story"          "The Breakfast Club"
```

Note that **arrays are created column-wise**. Did you also notice that there were only 9 movie names, but the array was 4 x 3? The original **vector doesn't have enough elements** to fill the entire array (that should have 3 x 4 = 12 elements). So R simply fills rest of the empty values by going back to the beginning of the vector and starting again ("Akira", "Toy story", "Room" in this case).

## Accessing Array Elements
```R
# Accessing Array Elements
movie_vector[1, 2, 1] # "The Breakfast Club"
movie_vector[1, 2, ] # "The Breakfast Club" "Modern Times"
movie_vector[1, , ] # "Toy Story" "The Breakfast Club" "Modern Times"
movie_vector[1, , 1] # "Toy Story" "The Breakfast Club" "Modern Times"
movie_vector[1, 1, ] # "Toy Story" "The Breakfast Club" "Modern Times"
```

## Using Logical Operators with Arrays

Let's have a look at the following example:

```R
mask_array <- length_array < 120
mask_array

x_vector <- c("Akira", "Toy Story", "Room", "The Wave", "Whiplash",
              "Star Wars", "The Ring", "The Artist", "Jumanji")
x_array <- array(x_vector, dim = c(3,3))

x_array[mask_array] # "Akira" "The Wave" "The Ring" "The Artist"
```

In this example, we created a logical vector called mask_array that contains the value TRUE for every element in length_array that is less than 120. We then used this logical vector to subset x_array. The result is a vector that contains the values of x_array that correspond to the TRUE values in mask_array.

# Matrices

Matrices are a subtype of arrays. A matrix must have 2 dimensions, whereas arrays are more flexible and can have, one, two, or more dimensions.

To create a matrix out of a vector , you can use matrix(), which takes in an argument for the vector, an argument for the number of rows and another for the number of column

```R
# Create a matrix
movie_matrix <- matrix(c("Toy Story", "Akira", "The Breakfast Club", "The Artist", "Modern Times"), nrow = 2, ncol = 3)

#      [,1]                  [,2]                  [,3]
# [1,] "Toy Story"            "The Breakfast Club" "Modern Times"
# [2,] "Akira"                "The Artist"         "Toy Story"
```

## Accessing Matrix Elements

As with arrays, you can use [row, column] to access elements of a matrix. To retrieve "Akira", you should use [1,1] as it lies in the first row and first column.

```R
# Accessing Matrix Elements
movie_matrix[1, 2] # "The Breakfast Club"
movie_matrix[1, ] # "Toy Story" "The Breakfast Club" "Modern Times"
movie_matrix[, 2] # "The Breakfast Club" "The Artist"
movie_matrix[1:2, 1:2] # "Toy Story" "Akira" "The Breakfast Club" "The Artist"
```

## Concatenation function

A concatenation function is used to combine two vectors into one vector. It combines values of both vectors.
Lets create a new vector for the upcoming movies as a upcoming_movie variable and add them to the movie_vector variable to create a new_vector of movies.

```R
upcoming_movie <- c("Fast and Furious X", "xXx: Return of Xander Cage", "Suicide Squad")
new_vector <- c(movie_vector, upcoming_movie)
new_vector
```