# Data Transformation in Pandas

In [1]:
import pandas as pd

In [2]:
data=pd.DataFrame({"a":["one","two"]*3,
                   "b":[1,1,2,3,2,3]})
data

a  b
0  one  1
1  two  1
2  one  2
3  two  3
4  one  2
5  two  3

In [3]:
data.duplicated()

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [4]:
data.drop_duplicates()

a  b
0  one  1
1  two  1
2  one  2
3  two  3

In [5]:
data["c"]=range(6)
data

a  b  c
0  one  1  0
1  two  1  1
2  one  2  2
3  two  3  3
4  one  2  4
5  two  3  5

In [6]:
data.duplicated(["a","b"],keep="last")

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [7]:
df=pd.DataFrame({"names":["Tim","tom","Sam",
                          "kate","Kim"],
                "scores":[60,50,70,80,40]})
df

names  scores
0   Tim      60
1   tom      50
2   Sam      70
3  kate      80
4   Kim      40

In [8]:
classes={"Tim":"A","Tom":"A","Sam":"B",
         "Kate":"B","Kim":"B"}

In [9]:
n=df["names"].str.capitalize()

In [10]:
df["branches"]=n.map(classes)

In [11]:
df

names  scores branches
0   Tim      60        A
1   tom      50        A
2   Sam      70        B
3  kate      80        B
4   Kim      40        B

In [12]:
s=pd.Series([80,70,90,60])
s

0    80
1    70
2    90
3    60
dtype: int64

In [13]:
import numpy as np

In [14]:
s.replace(70,np.nan)

0    80.0
1     NaN
2    90.0
3    60.0
dtype: float64

In [15]:
s.replace([70,60],[np.nan,0])

0    80.0
1     NaN
2    90.0
3     0.0
dtype: float64

In [16]:
s.replace({90:100,60:0})

0     80
1     70
2    100
3      0
dtype: int64

In [17]:
df=pd.DataFrame(
    np.arange(12).reshape(3,4),
    index=[0,1,2],
    columns=["tim","tom","kim","sam"])
df

tim  tom  kim  sam
0    0    1    2    3
1    4    5    6    7
2    8    9   10   11

In [18]:
s=pd.Series(["one","two","three"])
df.index=df.index.map(s)

In [19]:
df

tim  tom  kim  sam
one      0    1    2    3
two      4    5    6    7
three    8    9   10   11

In [20]:
df.rename(index=str.title,columns=str.upper)

TIM  TOM  KIM  SAM
One      0    1    2    3
Two      4    5    6    7
Three    8    9   10   11

In [21]:
df.rename(index={"one":"ten"},
          columns={"sam":"kate"},
          inplace=True)
df

tim  tom  kim  kate
ten      0    1    2     3
two      4    5    6     7
three    8    9   10    11

In [22]:
sc=[30,80,40,90,60,45,95,75,55,100,65,85]

In [23]:
x=[20,40,60,80,100]

In [24]:
y=pd.cut(sc,x)
y

[(20, 40], (60, 80], (20, 40], (80, 100], (40, 60], ..., (60, 80], (40, 60], (80, 100], (60, 80], (80, 100]]
Length: 12
Categories (4, interval[int64]): [(20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [25]:
y.codes

array([0, 2, 0, 3, 1, 1, 3, 2, 1, 3, 2, 3], dtype=int8)

In [26]:
y.categories

IntervalIndex([(20, 40], (40, 60], (60, 80], (80, 100]],
              closed='right',
              dtype='interval[int64]')

In [27]:
pd.value_counts(y)

(80, 100]    4
(60, 80]     3
(40, 60]     3
(20, 40]     2
dtype: int64

In [28]:
y=pd.cut(sc,x,right=False)
y

[[20, 40), [80, 100), [40, 60), [80, 100), [60, 80), ..., [60.0, 80.0), [40.0, 60.0), NaN, [60.0, 80.0), [80.0, 100.0)]
Length: 12
Categories (4, interval[int64]): [[20, 40) < [40, 60) < [60, 80) < [80, 100)]

In [29]:
nm=["low", "medium", "high", "very high"]
pd.cut(sc,x,labels=nm)

['low', 'high', 'low', 'very high', 'medium', ..., 'high', 'medium', 'very high', 'high', 'very high']
Length: 12
Categories (4, object): ['low' < 'medium' < 'high' < 'very high']

In [30]:
pd.cut(sc,10)

[(29.93, 37.0], (79.0, 86.0], (37.0, 44.0], (86.0, 93.0], (58.0, 65.0], ..., (72.0, 79.0], (51.0, 58.0], (93.0, 100.0], (58.0, 65.0], (79.0, 86.0]]
Length: 12
Categories (10, interval[float64]): [(29.93, 37.0] < (37.0, 44.0] < (44.0, 51.0] < (51.0, 58.0] ... (72.0, 79.0] < (79.0, 86.0] < (86.0, 93.0] < (93.0, 100.0]]

In [31]:
data=np.random.randn(100)
c=pd.qcut(data,4)
c

[(-0.135, 0.631], (0.631, 2.286], (-0.629, -0.135], (0.631, 2.286], (-2.186, -0.629], ..., (-0.629, -0.135], (0.631, 2.286], (0.631, 2.286], (-0.135, 0.631], (-0.629, -0.135]]
Length: 100
Categories (4, interval[float64]): [(-2.186, -0.629] < (-0.629, -0.135] < (-0.135, 0.631] < (0.631, 2.286]]

In [32]:
pd.value_counts(c)

(0.631, 2.286]      25
(-0.135, 0.631]     25
(-0.629, -0.135]    25
(-2.186, -0.629]    25
dtype: int64

In [33]:
data=pd.DataFrame(np.random.randn(1000,4))
data.head()

0         1         2         3
0  0.661162 -1.315550  0.138893 -2.186859
1 -0.422096  0.587658 -0.478577 -0.285737
2 -0.283092 -0.021623  1.194335 -0.197599
3 -1.545286 -0.219977  0.353704  0.424970
4 -0.196521  3.491917  0.016217 -0.464119

In [34]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.048690     0.030168    -0.050958    -0.004881
std       0.991747     0.996656     0.992911     1.021762
min      -2.999425    -3.514219    -2.864107    -3.186480
25%      -0.723203    -0.622904    -0.726046    -0.752119
50%      -0.058605     0.027484    -0.036939     0.023319
75%       0.560961     0.654890     0.605512     0.739495
max       3.952527     3.491917     3.074154     3.002287

In [35]:
col=data[1]

In [36]:
col[np.abs(col)>3]

4      3.491917
117    3.098920
311   -3.067095
903   -3.514219
Name: 1, dtype: float64

In [37]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
4   -0.196521  3.491917  0.016217 -0.464119
117 -1.360727  3.098920 -0.902404 -1.874759
311 -1.408380 -3.067095 -0.034621 -1.377992
492 -0.508447 -0.264550 -2.246989 -3.096799
510  3.952527 -0.307437  1.160524  1.022866
547 -0.146700 -0.594890  3.074154 -0.198825
642  3.116662 -0.466845 -0.543486  0.038652
867  0.222411 -0.131135  0.618451  3.002287
903 -0.917298 -3.514219 -2.500715  0.259489
956  0.115918  1.314808 -0.220663 -3.186480

In [38]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0  1.0 -1.0
1 -1.0  1.0 -1.0 -1.0
2 -1.0 -1.0  1.0 -1.0
3 -1.0 -1.0  1.0  1.0
4 -1.0  1.0  1.0 -1.0

In [39]:
data=pd.DataFrame(
    np.arange(12).reshape(4,3))
data

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [40]:
rw=np.random.permutation(4)
rw

array([2, 3, 0, 1])

In [41]:
data.take(rw)

0   1   2
2  6   7   8
3  9  10  11
0  0   1   2
1  3   4   5

In [42]:
data.sample()

0   1   2
3  9  10  11

In [43]:
data.sample(n=2)

0  1  2
0  0  1  2
2  6  7  8

## Dummy Variable

In [44]:
data=pd.DataFrame(
    {"letter":["c","b","a","b","b","a"],
                   "number":range(6)})
data

letter  number
0      c       0
1      b       1
2      a       2
3      b       3
4      b       4
5      a       5

In [45]:
pd.get_dummies(data["letter"])

a  b  c
0  0  0  1
1  0  1  0
2  1  0  0
3  0  1  0
4  0  1  0
5  1  0  0

In [46]:
data=np.random.randn(10)
data

array([-0.47399816, -0.4700948 , -0.10090975, -0.49105714,  0.85748633,
       -2.17384891, -1.89062041,  1.15155524, -1.12043372,  0.82935199])

In [47]:
pd.get_dummies(pd.cut(data,4))

(-2.177, -1.342]  (-1.342, -0.511]  (-0.511, 0.32]  (0.32, 1.152]
0                 0                 0               1              0
1                 0                 0               1              0
2                 0                 0               1              0
3                 0                 0               1              0
4                 0                 0               0              1
5                 1                 0               0              0
6                 1                 0               0              0
7                 0                 0               0              1
8                 0                 1               0              0
9                 0                 0               0              1